name: Create Neon Branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Neon Branch
      run: |
        curl -X POST https://console.neon.tech/api/v1/projects/<project-id>/branches \
        -H "Authorization: Bearer ${{ secrets.NEON_API_KEY }}" \
        -d '{"name": "${{ github.head_ref }}"}'
